# Generated by Django 5.0.3 on 2024-03-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='pix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='speed_flag',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
