# Generated by Django 5.0.3 on 2024-03-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_uploadedimage_pix_uploadedimage_speed_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='pix',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
