# Generated by Django 5.0.3 on 2024-03-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_remove_uploadedimage_pix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='violation',
        ),
    ]
